### ISSUE TITLE
升级到 0.06 后报错

### ISSUE THREAD

**Issue by zaxlct** [noahlam/Miment#16]
### 执行 npm run dev 后提示
This dependency was not found:

* miment in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/zaxlct1/Desktop/vvv/tracker/pc/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?
type=script&index=0!./src/components/OrderCard.vue, ../public/directive.js

**Comment by noahlam** [comment]
修复了, 发布v0.0.7了 

```js
npm i miment@0.0.7
```
