### ISSUE TITLE
项目中若使用UglifyJs在一起会报错

### ISSUE THREAD

**Issue by Licoy** [noahlam/Miment#18]
[问题过程](https://segmentfault.com/q/1010000014607429)

最终发现去除minment即可

还望作者查看是何原因导致的

**Comment by noahlam** [comment]
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),

我试了用这个打包,没发现问题

**Comment by noahlam** [comment]
我看了一下你的webpack配置,发现还有一个
new HtmlWebpackPlugin({
            title: 'Watch Dog' + package.version,
            favicon: './ico.png',
            filename: '../index.html',
            template: '!!ejs-loader!./src/template/index.ejs',
            inject: false
        })
如果是ejs的话,应该是属于浏览器环境,要使用浏览器版本的.

**Comment by Licoy** [comment]
原来是这样啊，谢谢作者
