### ISSUE TITLE
格式化的BUG

### ISSUE THREAD

**Issue by xueyou2000** [noahlam/Miment#19]
再官网例子里的https://noahlam.github.io/Miment/dist/miment-min.js是正确的，可以成功解析
**2019-05-15T17:48:53.000+0800** 格式的日期字符串

但是`npm`包里的却不行, 只返回NaN-NaN-NaN, 版本都是`0.0.8`, 很奇怪

**Comment by noahlam** [comment]
这是一个 bug 

已经在 miment@0.0.9 里修复，请更新一下版本。
